#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

import oauth2 as oauth
import urllib
import sys

def oauth_req(url, http_method="GET", post_body=None, http_headers=None):
    consumer = oauth.Consumer(key="", secret="")
    token = oauth.Token(key="",
            secret="")
    client = oauth.Client(consumer, token)

    resp, content = client.request(
            url,
            method=http_method,
            body=post_body,
            headers=http_headers
            )
    return content

if len(sys.argv) == 2:
    #For Windows
    #a = "status=" + urllib.quote(sys.argv[1].decode('gb2312').encode('utf-8'))
    #For Linux
    a = "status=" + urllib.quote(sys.argv[1])
    print "Tweeting..."
    req = oauth_req(
            'http://api.twitter.com/1/statuses/update.xml',
            'POST',
            a)
    #print req
    print "Done."
else :
    print "Error Parameter"
